# Generated by Django 5.0.2 on 2024-02-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
